services:
  - type: web
    name: justartech-saas
    env: docker
    plan: starter
    region: frankfurt
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        sync: false
      - key: DB_CONNECTION
        value: sqlite
      - key: LOG_CHANNEL
        value: stderr
      - key: CACHE_DRIVER
        value: file
      - key: SESSION_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: APP_URL
        value: https://business_management_system-1.onrender.com/  # Update if using custom domain
      - key: ASSET_URL
        value: https://business_management_system-1.onrender.com/  # Update if using custom domain
    autoDeploy: true
